{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "database-user-operator.fullname" . }}
  labels:
    {{- include "database-user-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - path: /metrics
    port: https
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      {{- include "database-user-operator.selectorLabels" . | nindent 6 }}
{{- end }}
